#!/bin/bash
arg_file="$1"
interactive=""

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -i|--interactive) 
            interactive="--interactive"; shift ;;
        *)
            arg_file="$1"; shift ;;
    esac
done

if [[ -f "$arg_file" ]]; then
    name=$(basename "$arg_file" .arg)
    args=$(cat "$arg_file")
    pylint --disable C,W,R evo.py
    python evo.py --name $name $args $interactive
fi
